const data = {
    products: [
        {
            _id: '1',
            name: 'Flower Dress',
            category: 'Dresses',
            image: '/images/1.jpg',
            price: 120,
            countInStock: 89,
            brand: 'Ovie',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'White Dress',
            category: 'Dresses',
            image: '/images/2.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Ovie',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Flower Red Dress',
            category: 'Dresses',
            image: '/images/3.jpg',
            price: 120,
            countInStock: 2,
            brand: 'Ovie',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Blue Dress',
            category: 'Dresses',
            image: '/images/4.jpg',
            price: 120,
            countInStock: 14,
            brand: 'Ovie',
            rating: 5.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Green Dress',
            category: 'Dresses',
            image: '/images/5.jpg',
            price: 120,
            countInStock: 100,
            brand: 'Ovie',
            rating: 3.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Peach Dress',
            category: 'Dresses',
            image: '/images/6.jpg',
            countInStock: 0,
            price: 120,
            brand: 'Ovie',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality product',
        }
    ]
};


export default data;